### ISSUE TITLE
the ml-online example  can not found requirements.txt

### ISSUE THREAD

**Issue by liguodongIOT** [ploomber/projects#4]
I run it, found loss requirements.txt lead to run error

> from importlib import resources
>ImportError: cannot import name 'resources'

but I have installed **importlib** and **importlib-resources** in python 3.6 manually

<img width="1135" alt="ml-online-readme" src="https://user-images.githubusercontent.com/13220186/124578943-4255d180-de81-11eb-9261-c9283a180e82.png">

![ml-online](https://user-images.githubusercontent.com/13220186/124578969-4aae0c80-de81-11eb-9241-e843684d08ad.jpg)

**Comment by edublancas** [comment]
Hi,

Good catch! Thanks for reporting this.

`from importlib import resources` only works in python 3.7 and up.

If you're using python 3.6, change:

`from importlib import resources`

to:

`import importlib_resources  as resources`

Make sure you run `pip install importlib-resources` first.

let me know if that fixes the issue!
